"""baseline schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-24 00:48:33.040592
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Baseline schema - the create_all() state at the first public release.
    # Hand-verified identical to Base.metadata (tests/unit/test_migration_drift.py
    # keeps it so). Autogenerated then reviewed; do not edit - add a new revision.
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lore', sa.Text(), nullable=True),
    sa.Column('score_boost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hot_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('match_mode', sa.String(), nullable=False),
    sa.Column('boost', sa.Float(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('context_slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_voices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_index', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensitive_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('match_mode', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('context_slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_user', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_user', sa.Text(), nullable=True),
    sa.Column('summarized_at', sa.DateTime(), nullable=True),
    sa.Column('summary_context_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('analyze_started_at', sa.DateTime(), nullable=True),
    sa.Column('analyze_run_json', sa.Text(), nullable=True),
    sa.Column('proxy_path', sa.Text(), nullable=True),
    sa.Column('proxy_generated_at', sa.DateTime(), nullable=True),
    sa.Column('proxy_source_mtime', sa.Float(), nullable=True),
    sa.Column('proxy_source_size', sa.Integer(), nullable=True),
    sa.Column('parent_video_id', sa.Integer(), nullable=True),
    sa.Column('segment_start_s', sa.Float(), nullable=True),
    sa.Column('segment_end_s', sa.Float(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('source_uploader', sa.Text(), nullable=True),
    sa.Column('source_upload_date', sa.DateTime(), nullable=True),
    sa.Column('source_category', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_user', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_user', sa.Text(), nullable=True),
    sa.Column('timeline_json', sa.Text(), nullable=True),
    sa.Column('context_names_json', sa.Text(), nullable=True),
    sa.Column('transcript_edited_at', sa.DateTime(), nullable=True),
    sa.Column('clips_scored_at', sa.DateTime(), nullable=True),
    sa.Column('clips_scored_context_json', sa.Text(), nullable=True),
    sa.Column('summarized_at', sa.DateTime(), nullable=True),
    sa.Column('summary_context_json', sa.Text(), nullable=True),
    sa.Column('timeline_generated_at', sa.DateTime(), nullable=True),
    sa.Column('timeline_context_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_video_id'], ['videos.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('stream_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('relevance_weight', sa.Float(), nullable=False),
    sa.Column('do_transcribe', sa.Boolean(), nullable=False),
    sa.Column('do_score', sa.Boolean(), nullable=False),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('channel_layout', sa.String(), nullable=True),
    sa.Column('stream_title_tag', sa.String(), nullable=True),
    sa.Column('extracted_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('score_overall', sa.Float(), nullable=False),
    sa.Column('score_funny', sa.Float(), nullable=False),
    sa.Column('score_dramatic', sa.Float(), nullable=False),
    sa.Column('score_action', sa.Float(), nullable=False),
    sa.Column('score_visual', sa.Float(), nullable=False),
    sa.Column('score_overall_user', sa.Float(), nullable=True),
    sa.Column('score_laugh', sa.Float(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('user_tags_json', sa.Text(), nullable=True),
    sa.Column('transcript_excerpt', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_user', sa.Text(), nullable=True),
    sa.Column('description_long', sa.Text(), nullable=True),
    sa.Column('description_long_user', sa.Text(), nullable=True),
    sa.Column('start_offset', sa.Float(), nullable=False),
    sa.Column('end_offset', sa.Float(), nullable=False),
    sa.Column('crop_x', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('exported_container', sa.String(), nullable=True),
    sa.Column('exported_burn_subs', sa.Boolean(), nullable=True),
    sa.Column('exported_title_card', sa.Boolean(), nullable=True),
    sa.Column('exported_embed_subs', sa.Boolean(), nullable=True),
    sa.Column('hotword_matches_json', sa.Text(), nullable=True),
    sa.Column('hotword_boost_json', sa.Text(), nullable=True),
    sa.Column('sensitive_matches_json', sa.Text(), nullable=True),
    sa.Column('related_clips_json', sa.Text(), nullable=True),
    sa.Column('related_clips_at', sa.DateTime(), nullable=True),
    sa.Column('vision_summary', sa.Text(), nullable=True),
    sa.Column('vision_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('transcript_edited_at', sa.DateTime(), nullable=True),
    sa.Column('trim_edited_at', sa.DateTime(), nullable=True),
    sa.Column('description_edited_at', sa.DateTime(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('timecode_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_boundaries', schema=None) as batch_op:
        batch_op.create_index('ix_scene_boundaries_video_time', ['video_id', 'timecode_ms'], unique=False)

    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_index', sa.Integer(), nullable=False),
    sa.Column('voiceprint', sa.LargeBinary(), nullable=True),
    sa.Column('voiceprint_backend', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('suggested_match_id', sa.Integer(), nullable=True),
    sa.Column('suggested_match_score', sa.Float(), nullable=True),
    sa.Column('global_voice_id', sa.Integer(), nullable=True),
    sa.Column('suggested_voice_id', sa.Integer(), nullable=True),
    sa.Column('suggested_voice_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suggested_match_id'], ['speakers.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('timecode_ms', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visual_activity', schema=None) as batch_op:
        batch_op.create_index('ix_visual_activity_video_time', ['video_id', 'timecode_ms'], unique=False)

    op.create_table('audio_energy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_track_id', sa.Integer(), nullable=False),
    sa.Column('second_offset', sa.Integer(), nullable=False),
    sa.Column('rms_db', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['audio_track_id'], ['audio_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_energy', schema=None) as batch_op:
        batch_op.create_index('ix_audio_energy_track_second', ['audio_track_id', 'second_offset'], unique=False)

    op.create_table('clip_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('preset_name', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('container', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clip_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip_exports', schema=None) as batch_op:
        batch_op.create_index('ix_clip_exports_clip_id', ['clip_id'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_track_id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_track_id'], ['audio_tracks.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['clip_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_exemplars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_voice_id', sa.Integer(), nullable=False),
    sa.Column('voiceprint', sa.LargeBinary(), nullable=False),
    sa.Column('voiceprint_backend', sa.String(), nullable=True),
    sa.Column('source_speaker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_voice_id'], ['project_voices.id'], ),
    sa.ForeignKeyConstraint(['source_speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('speaker_label', sa.String(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('speaker_edited', sa.Boolean(), nullable=False),
    sa.Column('words_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # Forward-only: recovery from a bad upgrade is restoring the pre-migration
    # backup file, never `alembic downgrade` (see docs/dev/ARCHITECTURE.md).
    raise NotImplementedError("yuu-clip migrations are forward-only")
