"""``yuu-dev bundle`` - concatenate the ordered static JS files into one bundle.js.

Step 1 of the frontend build step (WS5): the ~40 hand-ordered ``<script>`` tags in
index.html collapse to a single committed ``bundle.js`` whose load order lives in
``bundle.manifest``. This is deterministic ordered concatenation, NOT a module
bundler - every file stays a classic global-scope script, so top-level
``function foo(){}`` declarations remain global and the inline ``onclick="foo()"``
handlers keep working. Behavior is byte-for-byte identical to loading the files as
separate ``<script>`` tags.

The committed ``bundle.js`` is the artifact the server, packaging, and CI ship, so no
Node is needed anywhere. ``tests/unit/test_bundle_drift.py`` guards that the committed
file still matches the manifest; regenerate with ``yuu-dev bundle`` when it drifts.
"""
from __future__ import annotations

import time
from pathlib import Path

import typer

from yuu_clip.dev._base import REPO_ROOT, app, console

STATIC_DIR = REPO_ROOT / "yuu_clip" / "web" / "static"
MANIFEST_PATH = STATIC_DIR / "bundle.manifest"
BUNDLE_PATH = STATIC_DIR / "bundle.js"

_GENERATED_HEADER = (
    "// GENERATED by `yuu-dev bundle` from bundle.manifest - do not edit by hand.\n"
    "// Edit the individual static/*.js files (or the manifest order) and re-run\n"
    "// `yuu-dev bundle`. tests/unit/test_bundle_drift.py guards this file.\n"
)


def parse_manifest(text: str) -> list[str]:
    names: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        names.append(line)
    return names


def manifest_files() -> list[str]:
    return parse_manifest(MANIFEST_PATH.read_text(encoding="utf-8"))


def build_bundle() -> str:
    """Concatenate the manifest's files, each prefixed with a //# sourceURL banner so
    browser devtools still attributes code to the original filename."""
    sections = [_GENERATED_HEADER]
    for name in manifest_files():
        source = (STATIC_DIR / name).read_text(encoding="utf-8")
        if not source.endswith("\n"):
            source += "\n"
        sections.append(f"//# sourceURL={name}\n{source}")
    return "\n".join(sections)


def _write_bundle() -> None:
    BUNDLE_PATH.write_text(build_bundle(), encoding="utf-8", newline="\n")
    console.print(f"Wrote {BUNDLE_PATH} ({len(manifest_files())} files)")


def _watched_paths() -> list[Path]:
    return [MANIFEST_PATH, *(STATIC_DIR / name for name in manifest_files())]


def _snapshot() -> dict[Path, float]:
    snapshot: dict[Path, float] = {}
    for path in _watched_paths():
        try:
            snapshot[path] = path.stat().st_mtime
        except OSError:
            snapshot[path] = 0.0
    return snapshot


def _watch() -> None:
    console.print("[cyan](watching for changes - Ctrl+C to stop)[/cyan]")
    last = _snapshot()
    try:
        while True:
            time.sleep(0.5)
            current = _snapshot()
            if current != last:
                last = current
                _write_bundle()
    except KeyboardInterrupt:
        pass


@app.command("bundle")
def bundle(
    watch: bool = typer.Option(
        False, "--watch",
        help="Rebuild whenever a bundled file or the manifest changes (Ctrl+C to stop).",
    ),
) -> None:
    """Concatenate the manifest's static JS files into static/bundle.js."""
    if not MANIFEST_PATH.exists():
        console.print(f"[red]{MANIFEST_PATH} not found.[/red]")
        raise typer.Exit(1)
    _write_bundle()
    if watch:
        _watch()
