"""``yuu-dev bundle`` - build the web UI's two committed JS bundles.

The frontend ships two bundles that index.html loads in order:

1. ``bundle.esm.js`` - real ESM modules (import/export) bundled by **esbuild** from
   the graph rooted at ``main.esm.js`` (see ``scripts/build-esm.mjs``). This is the
   strangler-fig target (WS5 step 2): classic modules migrate here one at a time.
2. ``bundle.js`` - the remaining classic global-scope scripts, produced by
   deterministic ordered concatenation of the files in ``bundle.manifest`` (NOT a
   module bundler, so top-level ``function foo(){}`` stays global and the inline
   ``onclick="foo()"`` handlers keep working).

Both committed bundles are the artifacts the server, packaging, and CI ship - Node is
only needed to *rebuild* ``bundle.esm.js``, never to run the app.
``tests/unit/test_bundle_drift.py`` guards that both committed files are current;
regenerate with ``yuu-dev bundle`` when they drift.
"""
from __future__ import annotations

import shutil
import subprocess
import time
from pathlib import Path

import typer

from yuu_clip.dev._base import REPO_ROOT, app, console

STATIC_DIR = REPO_ROOT / "yuu_clip" / "web" / "static"
MANIFEST_PATH = STATIC_DIR / "bundle.manifest"
BUNDLE_PATH = STATIC_DIR / "bundle.js"
ESM_BUILD_SCRIPT = REPO_ROOT / "scripts" / "build-esm.mjs"
ESM_ENTRY = STATIC_DIR / "main.esm.js"
ESM_BUNDLE_PATH = STATIC_DIR / "bundle.esm.js"

_GENERATED_HEADER = (
    "// GENERATED by `yuu-dev bundle` from bundle.manifest - do not edit by hand.\n"
    "// Edit the individual static/*.js files (or the manifest order) and re-run\n"
    "// `yuu-dev bundle`. tests/unit/test_bundle_drift.py guards this file.\n"
)


def parse_manifest(text: str) -> list[str]:
    names: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        names.append(line)
    return names


def manifest_files() -> list[str]:
    return parse_manifest(MANIFEST_PATH.read_text(encoding="utf-8"))


def build_bundle() -> str:
    """Concatenate the manifest's files, each prefixed with a //# sourceURL banner so
    browser devtools still attributes code to the original filename."""
    sections = [_GENERATED_HEADER]
    for name in manifest_files():
        source = (STATIC_DIR / name).read_text(encoding="utf-8")
        if not source.endswith("\n"):
            source += "\n"
        sections.append(f"//# sourceURL={name}\n{source}")
    return "\n".join(sections)


def node_available() -> bool:
    return shutil.which("node") is not None


def esbuild_available() -> bool:
    """True when the ESM bundle can be (re)built here: Node on PATH and esbuild
    installed. The drift guard skips when this is False so `test-api` still passes
    offline / on a machine without the JS toolchain (bundle.esm.js is committed)."""
    return node_available() and (REPO_ROOT / "node_modules" / "esbuild").exists()


def build_esm_bundle(outfile: Path | None = None) -> None:
    """Run esbuild (via scripts/build-esm.mjs) to produce the ESM bundle.

    ``outfile`` overrides the default static/bundle.esm.js target - the drift guard
    passes a temp path in the same directory so its comparison copy is byte-identical.
    Raises RuntimeError if Node is missing or esbuild fails, so a stale ESM bundle
    can never pass silently as an up-to-date one.
    """
    if not node_available():
        raise RuntimeError(
            "Node.js is required to build bundle.esm.js but `node` is not on PATH. "
            "Install Node (https://nodejs.org) and run `npm install`, then retry "
            "`yuu-dev bundle`. The committed bundle.esm.js still ships without Node."
        )
    cmd = ["node", str(ESM_BUILD_SCRIPT)]
    if outfile is not None:
        cmd += ["--outfile", str(outfile)]
    proc = subprocess.run(cmd, cwd=str(REPO_ROOT), capture_output=True, text=True)
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout).strip()
        raise RuntimeError(
            f"esbuild failed (exit {proc.returncode}). Did you run `npm install`?\n{detail}"
        )


def _write_bundle() -> None:
    BUNDLE_PATH.write_text(build_bundle(), encoding="utf-8", newline="\n")
    console.print(f"Wrote {BUNDLE_PATH} ({len(manifest_files())} classic files)")
    build_esm_bundle()
    console.print(f"Wrote {ESM_BUNDLE_PATH} (esbuild, ESM graph from {ESM_ENTRY.name})")


def _watched_paths() -> list[Path]:
    """Every source that either bundle is built from: the classic manifest files, the
    manifest itself, and all ESM sources reachable from the entry. The ESM graph is not
    enumerable without parsing imports, so watch every static .js except the two
    generated bundles - any edit triggers a rebuild of both bundles."""
    generated = {BUNDLE_PATH, ESM_BUNDLE_PATH}
    esm_sources = [p for p in STATIC_DIR.glob("*.js") if p not in generated]
    return [MANIFEST_PATH, *esm_sources]


def _snapshot() -> dict[Path, float]:
    snapshot: dict[Path, float] = {}
    for path in _watched_paths():
        try:
            snapshot[path] = path.stat().st_mtime
        except OSError:
            snapshot[path] = 0.0
    return snapshot


def _watch() -> None:
    console.print("[cyan](watching for changes - Ctrl+C to stop)[/cyan]")
    last = _snapshot()
    try:
        while True:
            time.sleep(0.5)
            current = _snapshot()
            if current != last:
                last = current
                _write_bundle()
    except KeyboardInterrupt:
        pass


@app.command("bundle")
def bundle(
    watch: bool = typer.Option(
        False, "--watch",
        help="Rebuild whenever a bundled file or the manifest changes (Ctrl+C to stop).",
    ),
) -> None:
    """Concatenate the manifest's static JS files into static/bundle.js."""
    if not MANIFEST_PATH.exists():
        console.print(f"[red]{MANIFEST_PATH} not found.[/red]")
        raise typer.Exit(1)
    _write_bundle()
    if watch:
        _watch()
